const express = require("express");
const multer = require("multer");
const { exec } = require("child_process");
const fs = require("fs");
const path = require("path");

const app = express();
const upload = multer({ dest: "uploads/" });

app.get("/check-gs", (req, res) => {
  const { exec } = require("child_process");

  exec("which gs && gs --version", (err, stdout, stderr) => {
    if (err) {
      return res.status(500).json({
        success: false,
        error: err.message,
        stderr
      });
    }
    res.json({
      success: true,
      output: stdout
    });
  });
});

app.post("/split", upload.single("pdf"), (req, res) => {
  try {
    if (!req.file) {
      console.error("No file received");
      return res.status(400).json({ error: "No file uploaded" });
    }

    console.log("Uploaded file:", req.file);

    const inputPath = req.file.path;
    const jobId = Date.now().toString();
    const baseDir = path.join(__dirname, "files");
    const outputDir = path.join(baseDir, jobId);

    console.log("Creating output dir:", outputDir);
    fs.mkdirSync(outputDir, { recursive: true });

    const cmd = `/usr/bin/gs -dSAFER -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sOutputFile=${outputDir}/page_%03d.pdf ${inputPath}`;

    console.log("Running GS command:", cmd);

    exec(cmd, (error, stdout, stderr) => {
      console.log("GS STDOUT:", stdout);
      console.log("GS STDERR:", stderr);

      if (error) {
        console.error("GS EXEC ERROR:", error);
        return res.status(500).json({
          error: "Ghostscript failed",
          execError: error.message,
          stderr
        });
      }

      const files = fs.readdirSync(outputDir);
      console.log("Generated files:", files);

      if (!files.length) {
        return res.status(500).json({
          error: "No output files generated by Ghostscript"
        });
      }

      res.json(
        files.map(file => ({
          name: file,
          url: `/files/${jobId}/${file}`
        }))
      );
    });
  } catch (err) {
    console.error("SERVER CRASH:", err);
    res.status(500).json({ error: "Server exception", details: err.message });
  }
});

app.use("/files", express.static(path.join(__dirname, "files")));

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("Server running on port " + PORT));
